# Generated by Django 4.1.3 on 2022-11-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='olusma_date',
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.CharField(default=1, max_length=567),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='partOfSpeech',
            field=models.CharField(default=1, max_length=77),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=231),
        ),
    ]
